// <auto-generated />
using System;
using ASNAOrders.Web.Administration.Server.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASNAOrders.Web.Administration.Server.DataAccess.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20240519154139_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASNAOrders.Web.Administration.Server.DataAccess.EntityDataModels.UserEntityDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BanIssued")
                        .HasColumnType("bit");

                    b.Property<string>("BanReason")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EncryptedPasswordSalt")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("PermissionsId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ASNAOrders.Web.Administration.Server.DataAccess.EntityDataModels.UserPermissionsDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Operator")
                        .HasColumnType("bit");

                    b.Property<bool>("OptionsView")
                        .HasColumnType("bit");

                    b.Property<bool>("OptionsViewEdit")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ASNAOrders.Web.Administration.Server.DataAccess.EntityDataModels.UserEntityDataModel", b =>
                {
                    b.HasOne("ASNAOrders.Web.Administration.Server.DataAccess.EntityDataModels.UserPermissionsDataModel", "Permissions")
                        .WithMany()
                        .HasForeignKey("PermissionsId");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
