using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ASNAOrders.Web.Administration.Server.DataAccess.EntityDataModels
{
    [Table("Users")]
    public class UserEntityDataModel
    {
        /// <summary>
        /// Internal identifier of the user account.
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// User name of the account specified at registration.
        /// </summary>
        [Column]
        [StringLength(64)]
        public string? Username { get; set; }

        /// <summary>
        /// Password hash generated by stock SHA256 implementation.
        /// </summary>
        [Column]
        [StringLength(64)]
        public string? PasswordHash { get; set; }

        /// <summary>
        /// Encrypted password salt generated by ProtectedData.Protect().
        /// </summary>
        [Column]
        [StringLength(64)]
        public string? EncryptedPasswordSalt { get; set; }

        /// <summary>
        /// Determines whether the account is banned.
        /// </summary>
        [Column]
        public bool BanIssued { get; set; }

        /// <summary>
        /// If BanIssued set, determines the timestamp the user should be unbanned.
        /// </summary>
        [Column]
        public DateTime? BanTerm { get; set; }

        /// <summary>
        /// Determines permissions issued by operator.
        /// </summary>
        [InverseProperty(nameof(UserPermissionsDataModel.UserBinding))]
        public UserPermissionsDataModel Permissions { get; set; }
    }
}
