//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASNAOrders.Agent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASNAOrders.Agent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActiveIcon {
            get {
                object obj = ResourceManager.GetObject("ActiveIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActiveIconOrder {
            get {
                object obj = ResourceManager.GetObject("ActiveIconOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActiveIconStockUpload {
            get {
                object obj = ResourceManager.GetObject("ActiveIconStockUpload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгрузка текущих остатков в процессе передачи..
        /// </summary>
        internal static string ActiveStockUploadDescTray {
            get {
                return ResourceManager.GetString("ActiveStockUploadDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгрузка начата.
        /// </summary>
        internal static string ActiveStockUploadTitleTray {
            get {
                return ResourceManager.GetString("ActiveStockUploadTitleTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eventvwr.msc.
        /// </summary>
        internal static string BalloonTipClickedRun {
            get {
                return ResourceManager.GetString("BalloonTipClickedRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item_desc,category,price,qtty,item_id,item_name,country,composition,barcode.
        /// </summary>
        internal static string DbSelectedColumns {
            get {
                return ResourceManager.GetString("DbSelectedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DisabledIcon {
            get {
                object obj = ResourceManager.GetObject("DisabledIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorIcon {
            get {
                object obj = ResourceManager.GetObject("ErrorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка файловой системы. Для получения подробной информации см. Журнал событий. .
        /// </summary>
        internal static string ErrorMessageInfoFNFDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoFNFDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка службы: указанный файл не найден..
        /// </summary>
        internal static string ErrorMessageInfoFNFLog {
            get {
                return ResourceManager.GetString("ErrorMessageInfoFNFLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка SQL. Превышено допустимое время операции..
        /// </summary>
        internal static string ErrorMessageInfoSqlExcServerLog {
            get {
                return ResourceManager.GetString("ErrorMessageInfoSqlExcServerLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка выгрузки.
        /// </summary>
        internal static string ErrorMessageInfoTitleTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoTitleTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла прочая сетевая ошибка. Для получения подробной информации см. Журнал событий..
        /// </summary>
        internal static string ErrorMessageInfoWebDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoWebDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочая сетевая ошибка..
        /// </summary>
        internal static string ErrorMessageInfoWebLog {
            get {
                return ResourceManager.GetString("ErrorMessageInfoWebLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка SQL. Неверный формат запроса. .
        /// </summary>
        internal static string ErrorMessageSqlExcSyntaxLog {
            get {
                return ResourceManager.GetString("ErrorMessageSqlExcSyntaxLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Сообщение системы: .
        /// </summary>
        internal static string ExceptionMessageTrayLog {
            get {
                return ResourceManager.GetString("ExceptionMessageTrayLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Дата попытки выгрузки:.
        /// </summary>
        internal static string MigrationAttemptDateTrayLog {
            get {
                return ResourceManager.GetString("MigrationAttemptDateTrayLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ID миграции: .
        /// </summary>
        internal static string MigrationIdTrayLog {
            get {
                return ResourceManager.GetString("MigrationIdTrayLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASNAOrders: выгрузка завершена успешно..
        /// </summary>
        internal static string MigrationSuccessDescTrayLog {
            get {
                return ResourceManager.GetString("MigrationSuccessDescTrayLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгрузка завершена.
        /// </summary>
        internal static string MigrationSuccessTitleTray {
            get {
                return ResourceManager.GetString("MigrationSuccessTitleTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NormalIcon {
            get {
                object obj = ResourceManager.GetObject("NormalIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReadyIcon {
            get {
                object obj = ResourceManager.GetObject("ReadyIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Информация для администраторов: .
        /// </summary>
        internal static string StackTraceTrayLog {
            get {
                return ResourceManager.GetString("StackTraceTrayLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///info_str_11 as item_desc,
        ///pro_name as category,
        ///max(Str_Value4_04) as price,
        ///sum(ws_Prt.Prt_CurrQnt - isnull(ws_prt.Prt_Reserve, 0)) as qtty,
        ///cast(cmp_unicode as varchar) as item_id,
        ///cmp_name as item_name,
        ///cntr_name as country,
        ///rnp_name as composition,
        ///str_barcode as barcode
        ///			
        ///        from ws_Prt
        ///        where Prt_Qnt &gt; 0 and Prt_CurrQnt - isnull(Prt_Reserve, 0) &gt; 0 and Prt_DateClose is null
        ///            and Cmp_UniCode not in (select Lnk_CmpUniCode2 from Lnk) and Cmp_UniCode &gt; 1
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StdQuery {
            get {
                return ResourceManager.GetString("StdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploads.txt.
        /// </summary>
        internal static string UploadInfoStorageFile {
            get {
                return ResourceManager.GetString("UploadInfoStorageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WarngIcon {
            get {
                object obj = ResourceManager.GetObject("WarngIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
