//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASNAOrders.Agent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASNAOrders.Agent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActiveIcon {
            get {
                object obj = ResourceManager.GetObject("ActiveIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActiveIconOrder {
            get {
                object obj = ResourceManager.GetObject("ActiveIconOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActiveIconStockUpload {
            get {
                object obj = ResourceManager.GetObject("ActiveIconStockUpload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгрузка текущих остатков в процессе передачи..
        /// </summary>
        internal static string ActiveStockUploadDescTray {
            get {
                return ResourceManager.GetString("ActiveStockUploadDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгрузка начата.
        /// </summary>
        internal static string ActiveStockUploadTitleTray {
            get {
                return ResourceManager.GetString("ActiveStockUploadTitleTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asna-orders.
        /// </summary>
        internal static string AsnaOrders {
            get {
                return ResourceManager.GetString("AsnaOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to к вашим услугам.
        /// </summary>
        internal static string AtYourService {
            get {
                return ResourceManager.GetString("AtYourService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eventvwr.msc.
        /// </summary>
        internal static string BalloonTipClickedRun {
            get {
                return ResourceManager.GetString("BalloonTipClickedRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to administrator.
        /// </summary>
        internal static string ConfigMQPassword {
            get {
                return ResourceManager.GetString("ConfigMQPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to administrator.
        /// </summary>
        internal static string ConfigMQUsername {
            get {
                return ResourceManager.GetString("ConfigMQUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item_desc,category,price,qtty,item_id,item_name,country,composition,barcode.
        /// </summary>
        internal static string DbSelectedColumns {
            get {
                return ResourceManager.GetString("DbSelectedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DisabledIcon {
            get {
                object obj = ResourceManager.GetObject("DisabledIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorIcon {
            get {
                object obj = ResourceManager.GetObject("ErrorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка парсинга данных. Для получения подробной информации см. Журнал событий..
        /// </summary>
        internal static string ErrorMessageInfoArgumentDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoArgumentDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка парсинга строки подключения. Для получения подробной информации см. Журнал событий..
        /// </summary>
        internal static string ErrorMessageInfoArgumentInitializationDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoArgumentInitializationDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка парсинга строки подключения. .
        /// </summary>
        internal static string ErrorMessageInfoArgumentInitializationLog {
            get {
                return ResourceManager.GetString("ErrorMessageInfoArgumentInitializationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка парсинга данных. .
        /// </summary>
        internal static string ErrorMessageInfoArgumentLog {
            get {
                return ResourceManager.GetString("ErrorMessageInfoArgumentLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка файловой системы. Для получения подробной информации см. Журнал событий. .
        /// </summary>
        internal static string ErrorMessageInfoFNFDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoFNFDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка службы: указанный файл не найден. .
        /// </summary>
        internal static string ErrorMessageInfoFNFLog {
            get {
                return ResourceManager.GetString("ErrorMessageInfoFNFLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла прочая ошибка. Для получения подробной информации см. Журнал событий..
        /// </summary>
        internal static string ErrorMessageInfoGenericDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoGenericDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла прочая ошибка. .
        /// </summary>
        internal static string ErrorMessageInfoGenericLog {
            get {
                return ResourceManager.GetString("ErrorMessageInfoGenericLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка парсинга списка столбцов. Неверный формат данных. Для получения подробной информации см. Журнал событий..
        /// </summary>
        internal static string ErrorMessageInfoIndexOORDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoIndexOORDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка парсинга списка столбцов. Неверный формат данных. .
        /// </summary>
        internal static string ErrorMessageInfoIndexOORLog {
            get {
                return ResourceManager.GetString("ErrorMessageInfoIndexOORLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка сети/валидации. Для получения подробной информации см. Журнал событий..
        /// </summary>
        internal static string ErrorMessageInfoInvOpDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoInvOpDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка сети/валидации. .
        /// </summary>
        internal static string ErrorMessageInfoInvOpLog {
            get {
                return ResourceManager.GetString("ErrorMessageInfoInvOpLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка парсинга БД. Для получения подробной информации см. Журнал событий..
        /// </summary>
        internal static string ErrorMessageInfoIOORDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoIOORDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка парсинга БД. .
        /// </summary>
        internal static string ErrorMessageInfoIOORLog {
            get {
                return ResourceManager.GetString("ErrorMessageInfoIOORLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка базы данных. Для получения подробной информации см. Журнал событий..
        /// </summary>
        internal static string ErrorMessageInfoSqlExcServerDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoSqlExcServerDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка SQL. Превышено допустимое время операции. .
        /// </summary>
        internal static string ErrorMessageInfoSqlExcServerLog {
            get {
                return ResourceManager.GetString("ErrorMessageInfoSqlExcServerLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла прочая ошибка базы данных. Для получения подробной информации см. Журнал событий..
        /// </summary>
        internal static string ErrorMessageInfoSqlExcSyntaxDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoSqlExcSyntaxDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка выгрузки.
        /// </summary>
        internal static string ErrorMessageInfoTitleTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoTitleTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла прочая сетевая ошибка. Для получения подробной информации см. Журнал событий..
        /// </summary>
        internal static string ErrorMessageInfoWebDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoWebDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочая сетевая ошибка. .
        /// </summary>
        internal static string ErrorMessageInfoWebLog {
            get {
                return ResourceManager.GetString("ErrorMessageInfoWebLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка парсинга XML-информации. Для получения подробной информации см. Журнал событий..
        /// </summary>
        internal static string ErrorMessageInfoXMLDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoXMLDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка парсинга XML-информации. .
        /// </summary>
        internal static string ErrorMessageInfoXMLLog {
            get {
                return ResourceManager.GetString("ErrorMessageInfoXMLLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка парсинга XML-информации. Для получения подробной информации см. Журнал событий..
        /// </summary>
        internal static string ErrorMessageInfoXMLRootDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageInfoXMLRootDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка парсинга XML-информации. .
        /// </summary>
        internal static string ErrorMessageInfoXMLRootLog {
            get {
                return ResourceManager.GetString("ErrorMessageInfoXMLRootLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка RabbitMQ. Для получения подробной информации см. Журнал событий..
        /// </summary>
        internal static string ErrorMessageRabbitMQDescTray {
            get {
                return ResourceManager.GetString("ErrorMessageRabbitMQDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка RabbitMQ..
        /// </summary>
        internal static string ErrorMessageRabbitMQLog {
            get {
                return ResourceManager.GetString("ErrorMessageRabbitMQLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка RabbitMQ.
        /// </summary>
        internal static string ErrorMessageRabbitMQTitleTray {
            get {
                return ResourceManager.GetString("ErrorMessageRabbitMQTitleTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка SQL. Неверный формат запроса. .
        /// </summary>
        internal static string ErrorMessageSqlExcSyntaxLog {
            get {
                return ResourceManager.GetString("ErrorMessageSqlExcSyntaxLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Сообщение системы: .
        /// </summary>
        internal static string ExceptionMessageTrayLog {
            get {
                return ResourceManager.GetString("ExceptionMessageTrayLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Дата попытки выгрузки:.
        /// </summary>
        internal static string MigrationAttemptDateTrayLog {
            get {
                return ResourceManager.GetString("MigrationAttemptDateTrayLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Дата выгрузки: .
        /// </summary>
        internal static string MigrationDatePrepend {
            get {
                return ResourceManager.GetString("MigrationDatePrepend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ИД выгрузки: .
        /// </summary>
        internal static string MigrationIdTrayLog {
            get {
                return ResourceManager.GetString("MigrationIdTrayLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начата выгрузка остатков. .
        /// </summary>
        internal static string MigrationStartedTitleLog {
            get {
                return ResourceManager.GetString("MigrationStartedTitleLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгрузка начата.
        /// </summary>
        internal static string MigrationStartedTitleTray {
            get {
                return ResourceManager.GetString("MigrationStartedTitleTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASNAOrders: выгрузка завершена успешно. .
        /// </summary>
        internal static string MigrationSuccessDescTrayLog {
            get {
                return ResourceManager.GetString("MigrationSuccessDescTrayLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгрузка завершена.
        /// </summary>
        internal static string MigrationSuccessTitleTray {
            get {
                return ResourceManager.GetString("MigrationSuccessTitleTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щелкните, чтобы принять. Сервер автоматически отменит заказ через 10 секунд..
        /// </summary>
        internal static string NewOrderDescTray {
            get {
                return ResourceManager.GetString("NewOrderDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ обнаружен..
        /// </summary>
        internal static string NewOrderLog {
            get {
                return ResourceManager.GetString("NewOrderLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас новый заказ.
        /// </summary>
        internal static string NewOrderTitleTray {
            get {
                return ResourceManager.GetString("NewOrderTitleTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NormalIcon {
            get {
                object obj = ResourceManager.GetObject("NormalIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notification.
        /// </summary>
        internal static string NotifyQueueProperty {
            get {
                return ResourceManager.GetString("NotifyQueueProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ИД заказа: .
        /// </summary>
        internal static string OrderIdPrepend {
            get {
                return ResourceManager.GetString("OrderIdPrepend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orders.
        /// </summary>
        internal static string OrdersQueueProperty {
            get {
                return ResourceManager.GetString("OrdersQueueProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состав заказа:  .
        /// </summary>
        internal static string OrderStringCompositionMsgbox {
            get {
                return ResourceManager.GetString("OrderStringCompositionMsgbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИД заказа:  .
        /// </summary>
        internal static string OrderStringIdMsgbox {
            get {
                return ResourceManager.GetString("OrderStringIdMsgbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итого:  .
        /// </summary>
        internal static string OrderStringPriceMsgbox {
            get {
                return ResourceManager.GetString("OrderStringPriceMsgbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ принят.
        /// </summary>
        internal static string OrderStringTitleMsgbox {
            get {
                return ResourceManager.GetString("OrderStringTitleMsgbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to farmoffice.ru.
        /// </summary>
        internal static string RabbitmqLocal {
            get {
                return ResourceManager.GetString("RabbitmqLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReadyIcon {
            get {
                object obj = ResourceManager.GetObject("ReadyIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Информация для администраторов: .
        /// </summary>
        internal static string StackTraceTrayLog {
            get {
                return ResourceManager.GetString("StackTraceTrayLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///info_str_11 as item_desc,
        ///pro_name as category,
        ///max(Str_Value4_04) as price,
        ///sum(ws_Prt.Prt_CurrQnt - isnull(ws_prt.Prt_Reserve, 0)) as qtty,
        ///cast(cmp_unicode as varchar) as item_id,
        ///cmp_name as item_name,
        ///cntr_name as country,
        ///rnp_name as composition,
        ///str_barcode as barcode
        ///			
        ///        from ws_Prt
        ///        where Prt_Qnt &gt; 0 and Prt_CurrQnt - isnull(Prt_Reserve, 0) &gt; 0 and Prt_DateClose is null
        ///            and Cmp_UniCode not in (select Lnk_CmpUniCode2 from Lnk) and Cmp_UniCode &gt; 1
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StdQuery {
            get {
                return ResourceManager.GetString("StdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asna.
        /// </summary>
        internal static string UploadJobGroup {
            get {
                return ResourceManager.GetString("UploadJobGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asna-stock-uploads.
        /// </summary>
        internal static string UploadJobName {
            get {
                return ResourceManager.GetString("UploadJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to версия.
        /// </summary>
        internal static string VersionWord {
            get {
                return ResourceManager.GetString("VersionWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WarngIcon {
            get {
                object obj = ResourceManager.GetObject("WarngIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указаны данные подключения к базе данных. Выгрузка прервана. .
        /// </summary>
        internal static string WarningInfoDBCredsNotSetDescTray {
            get {
                return ResourceManager.GetString("WarningInfoDBCredsNotSetDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение: не указаны данные подключения к БД. .
        /// </summary>
        internal static string WarningInfoDBCredsNotSetLog {
            get {
                return ResourceManager.GetString("WarningInfoDBCredsNotSetLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указаны данные подключения к FTP-серверу. Выгрузка прервана..
        /// </summary>
        internal static string WarningInfoFTPCredsNotSetDescTray {
            get {
                return ResourceManager.GetString("WarningInfoFTPCredsNotSetDescTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение: не указаны данные подключения к FTP-серверу..
        /// </summary>
        internal static string WarningInfoFTPCredsNotSetLog {
            get {
                return ResourceManager.GetString("WarningInfoFTPCredsNotSetLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        internal static string WarningInfoTitleTray {
            get {
                return ResourceManager.GetString("WarningInfoTitleTray", resourceCulture);
            }
        }
    }
}
