/*
 * API для интеграции сервиса Яндекс.Еда
 *
 * Описание API для работы с сервисом Яндекс.Еда по моделям \"Доставка Яндекс Едой\",  \"Доставка партнером\" и \"Самовывоз\". Все методы описанные ниже должны быть реализованы на стороне партнера в процессе интеграции. Т.е. сервис Яндекс.Еда выступает в роли клиента, а Вам необходимо реализовать серверную часть. Взаимодействие происходит на основании pull-модели, т.е. сервис Яндекс Еда как клиент запрашивает данные либо может создавать/обновлять данные если это необходимо.  # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * The version of the OpenAPI document: 1.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using ASNAOrders.Web.Converters;

namespace ASNAOrders.Web.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PickupOrderV1PromosInner : IEquatable<PickupOrderV1PromosInner>
    {
        /// <summary>
        /// Параметр не поддерживается в интеграции магазинов и передается пустым - GIFT - PERCENTAGE - FIXED
        /// </summary>
        /// <value>Параметр не поддерживается в интеграции магазинов и передается пустым - GIFT - PERCENTAGE - FIXED</value>
        /// <example>FIXED</example>
        [Required]
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Сума скидки в валюте
        /// </summary>
        /// <value>Сума скидки в валюте</value>
        /// <example>0</example>
        [Required]
        [DataMember(Name = "discount", EmitDefaultValue = true)]
        public decimal Discount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PickupOrderV1PromosInner {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Discount: ").Append(Discount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PickupOrderV1PromosInner)obj);
        }

        /// <summary>
        /// Returns true if PickupOrderV1PromosInner instances are equal
        /// </summary>
        /// <param name="other">Instance of PickupOrderV1PromosInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PickupOrderV1PromosInner other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) &&
                (
                    Discount == other.Discount ||

                    Discount.Equals(other.Discount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();

                hashCode = hashCode * 59 + Discount.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(PickupOrderV1PromosInner left, PickupOrderV1PromosInner right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PickupOrderV1PromosInner left, PickupOrderV1PromosInner right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
