/*
 * API для интеграции сервиса Яндекс.Еда
 *
 * Описание API для работы с сервисом Яндекс.Еда по моделям \"Доставка Яндекс Едой\",  \"Доставка партнером\" и \"Самовывоз\". Все методы описанные ниже должны быть реализованы на стороне партнера в процессе интеграции. Т.е. сервис Яндекс.Еда выступает в роли клиента, а Вам необходимо реализовать серверную часть. Взаимодействие происходит на основании pull-модели, т.е. сервис Яндекс Еда как клиент запрашивает данные либо может создавать/обновлять данные если это необходимо.  # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * The version of the OpenAPI document: 1.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using ASNAOrders.Web.Converters;

namespace ASNAOrders.Web.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SlotsCheckoutResponse : IEquatable<SlotsCheckoutResponse>
    {
        /// <summary>
        /// Gets or Sets DeliveryTimes
        /// </summary>
        [Required]
        [DataMember(Name="delivery_times", EmitDefaultValue=false)]
        public List<SlotsCheckoutResponseDeliveryTimesInner> DeliveryTimes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SlotsCheckoutResponse {\n");
            sb.Append("  DeliveryTimes: ").Append(DeliveryTimes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SlotsCheckoutResponse)obj);
        }

        /// <summary>
        /// Returns true if SlotsCheckoutResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of SlotsCheckoutResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SlotsCheckoutResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    DeliveryTimes == other.DeliveryTimes ||
                    DeliveryTimes != null &&
                    other.DeliveryTimes != null &&
                    DeliveryTimes.SequenceEqual(other.DeliveryTimes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (DeliveryTimes != null)
                    hashCode = hashCode * 59 + DeliveryTimes.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SlotsCheckoutResponse left, SlotsCheckoutResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SlotsCheckoutResponse left, SlotsCheckoutResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
